<?php
 // module/Application/view/application/book/index.phtml:

 $title = 'Books';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('book', array('action'=>'add'));?>">Add new book</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Isbn</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($books as $book) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($book->getTitle());?></td>
     <td><?php echo $this->escapeHtml($book->getIsbn());?></td>
     <td>
         <a href="<?php echo $this->url('book', array('action'=>'edit', 'id' => $book->getId() ));?>">Edit</a>
         <a href="<?php echo $this->url('book', array('action'=>'delete', 'id' => $book->getId() ));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>