<?php

namespace DoctrineORMModule\Proxy\__CG__\Domain\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book extends \Domain\Entity\Book implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'id', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'title', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'description', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'isbn', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'isbn13', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'published', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'language', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'cover', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'chapters');
        }

        return array('__isInitialized__', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'id', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'title', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'description', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'isbn', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'isbn13', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'published', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'language', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'cover', '' . "\0" . 'Domain\\Entity\\Book' . "\0" . 'chapters');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Book $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbn($isbn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbn', array($isbn));

        return parent::setIsbn($isbn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbn', array());

        return parent::getIsbn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsbn13($isbn13)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsbn13', array($isbn13));

        return parent::setIsbn13($isbn13);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsbn13()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsbn13', array());

        return parent::getIsbn13();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublished($published)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublished', array($published));

        return parent::setPublished($published);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublished', array());

        return parent::getPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array());

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function addChapter(\Domain\Entity\Chapter $chapter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChapter', array($chapter));

        return parent::addChapter($chapter);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChapter(\Domain\Entity\Chapter $chapter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChapter', array($chapter));

        return parent::removeChapter($chapter);
    }

    /**
     * {@inheritDoc}
     */
    public function getChapters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChapters', array());

        return parent::getChapters();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCover($cover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCover', array($cover));

        return parent::setCover($cover);
    }

    /**
     * {@inheritDoc}
     */
    public function getCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', array());

        return parent::getCover();
    }

}
